### ISSUE TITLE
Nextcloud 21 web check step

### ISSUE THREAD

**Issue by mchugh19** [rseabra/zabbix-templates#1]
On my newly installed nextcloud 21, the "Forgot your password?" step of the web check now seems to read 'Forgot password?". However, when accessing the site with curl, that text isn't displayed (I'm guessing it needs javascript to render). So perhaps the match should be on the footer which reads "a safe home for all your data".

**Comment by rseabra** [comment]
Hi, I'm truly sorry for taking almost two years to notice I had activity in this repo. Thanks for your alert, as the web scenario doesn't have a trigger associated with it yet I hadn't even noticed that.

In any case, I took your suggestion but used a string from the login form to check, just in case someone changes the footer for something custom.

Thanks and sorry for the delay,
Rui
